### ISSUE TITLE
There is no "vendor" folder in bootstrap for Popper.

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2-bootstrap4#47] opened 2018-07-24 17:44 UTC
### What steps will reproduce the problem?
I used yii2-bootstrap4. That's all. When I am using PopperAsset it's giving the "The file or directory to be published does not exist: /../../vendor/bower-asset/bootstrap/assets/js/vendor".  Seems the path is wrong. And seems right path: @bower/bootstrap/site/docs/4.1/assets/js/vendor

Link: https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/assets/js/vendor/popper.min.js

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.16
| PHP version      | 7.2
| Operating system | Linux

**Comment by rob006** [comment] 2018-07-24 19:50
Duplicate of #44

**Closed by rob006** 2018-07-24 19:50 UTC
