### ISSUE TITLE
bootstrap css not loading in some views

### ISSUE THREAD

**Issue by srakl** [yiisoft/yii2-bootstrap4#210] opened 2021-06-15 15:47 UTC
On some  pages the bootstrap css doesn't load properly. and on some it does. But when i view page source. the bootstrap.css is there. 

Any idea why? or how to fix this?

My AppAsset looks like this,

```
<?php

namespace frontend\assets;

use yii\web\AssetBundle;

/**
 * Main frontend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
       'css/site.css',
    ];
    public $js = [
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap4\BootstrapAsset',
         // here we add our FontAwesomeAsset bundle class
        'frontend\assets\FontAwesomeAsset'
    ];
}
```

things like this don't work, the `panel` doesn't have borders and title is white

```
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <img class="img-rounded" src="//gravatar.com/avatar/?s=24" alt="">                    </h3>
        <ul id="w0" class="nav flex-column nav-pills"><li class="nav-item"><a class="nav-link" href="/yii2/frontend/web/index.php?r=user%2Fsettings%2Fprofile">Edit Profile</a></li>

<li class="nav-item"><a class="nav-link active" href="/yii2/frontend/web/index.php?r=user%2Fsettings%2Fnetworks">Networks</a></li></ul>
        <ul id="w1" class="nav flex-column nav-pills"><li class="nav-item"><a class="nav-link" href="/yii2/frontend/web/index.php?r=user%2Fsettings%2Fprofile">Reports Purchased</a></li></ul>
    </div>
</div>
```

**Comment by samdark** [comment] 2021-06-15 16:36
No idea why. Maybe CSS rendering is blocker or something overrides it.

Closing the issue because without details we cannot reproduce it and thus cannot fix it.

**Closed by samdark** 2021-06-15 16:36 UTC
